[package]
name = "apc40mk2-router"
authors = ["David Frings, aka DevOpsDavid"]
version = "1.0.0"
description = "This is the API / backend from the Official PaRaMeRoS Website"
license = "MIT"
rust-version = "1.87"
edition = "2024"

[dependencies]
midir = "0.8.0"           # MIDI I/O library
wmidi = "4.0.6"           # MIDI message parsing and construction
clap = { version = "4.1.4", features = ["derive"] } # Command line argument parsing
anyhow = "1.0.68"         # Error handling
log = "0.4.17"            # Logging
env_logger = "0.10.0"     # Logger implementation
serde = { version = "1.0.152", features = ["derive"] } # For configuration
serde_json = "1.0.91"     # JSON config files
once_cell = "1.17.0"      # Lazy statics